ronreiter/interactive-tutorials

tutorials/learn-cpp.org/de/Generic Programming.md
tutorials/learn-cpp.org/de/Hello, World!.md
tutorials/learn-cpp.org/de/Inheritance.md
tutorials/learn-cpp.org/de/Variables and Types.md
tutorials/learn-cpp.org/de/Welcome.md
tutorials/learn-cpp.org/de/World!, Hello.md

Translated all found files into German.

German Translation for C++

---

tutorials/learnshell.org/de/Arrays.md
tutorials/learnshell.org/de/Basic Operators.md
tutorials/learnshell.org/de/Basic String Operations.md
tutorials/learnshell.org/de/Contributing Tutorials.md
tutorials/learnshell.org/de/Decision Making.md
tutorials/learnshell.org/de/Hello, World!.md
tutorials/learnshell.org/de/Loops.md
tutorials/learnshell.org/de/Passing Arguments to the Script.md
tutorials/learnshell.org/de/Shell Functions.md
tutorials/learnshell.org/de/Variables.md
tutorials/learnshell.org/de/Welcome.md

German translation of every file in en/ .

German Translation Shell

---

tutorials/learnshell.org/en/Decision Making.md
tutorials/learnshell.org/en/Loops.md
tutorials/learnshell.org/en/Shell Functions.md
tutorials/learnshell.org/en/Variables.md

Several fixes and typos for the Shell tutorials I found while translation them.

Several fixes for the English Shell tutorials

---

tutorials/learn-c.org/de/Arrays.md
tutorials/learn-c.org/de/Binary trees.md
tutorials/learn-c.org/de/Bitmasks.md
tutorials/learn-c.org/de/Contributing Tutorials.md
tutorials/learn-c.org/de/Dynamic allocation.md
tutorials/learn-c.org/de/For loops.md
tutorials/learn-c.org/de/Function Pointers.md
tutorials/learn-c.org/de/Function arguments by reference.md
tutorials/learn-c.org/de/Functions.md
tutorials/learn-c.org/de/Hello, World!.md
tutorials/learn-c.org/de/Linked lists.md
tutorials/learn-c.org/de/Pointer Arithmetics.md
tutorials/learn-c.org/de/Pointers.md
tutorials/learn-c.org/de/Recursion.md
tutorials/learn-c.org/de/Strings.md
tutorials/learn-c.org/de/Structures.md
tutorials/learn-c.org/de/Variables and Types.md
tutorials/learn-c.org/de/Welcome.md
tutorials/learn-c.org/de/While loops.md

Adds German translation of every file in tutorials/learn-c.org/en/.

German Translation C

---

tutorials/learn-c.org/en/Pointer Arithmetics.md

The instructions ask for the ADDRESS of each element to be printed, not the value

Fix error in Pointer Arithmetic tutorial

---

tutorials/learnpython.org/en/Basic String Operations.md
tutorials/learnpython.org/es/Basic String Operations.md

I updated the Basic string operations in python to say "thirteenth" instead of "twelfth" since s[12] is index 12, which is the 13th character in the string.

Update text appropriately based on 0-based indext

---

tutorials/learn-perl.org/en/Variables and Types.md

Update Variables and Types.md

---

tutorials/learncs.org/en/While loops.md

I'm new to the language, but I think the solution is incorrect. Please correct me if I'm wrong, thanks!

Update While loops.md

---

tutorials/learnjavaonline.org/en/Compiling and Running with Arguments.md

Solution is :
public class Main {
public static void main(String[] args) {
// write your code here
for (int i=0; i<args.length; i++)
{
System.out.println(args[i]);   
}
}
}

Update Compiling and Running with Arguments.md

---

tutorials/learncs.org/en/Methods.md

Small insignificant change, but the chapter looks more professional without the typo imho.

Fixed typo

---

tutorials/learnpython.org/pt/Basic Operators.md

Translate the original tutorial

Create Basic Operators.md

---

tutorials/learnjavaonline.org/en/Try and Catch.md

Corrected one word!

---

tutorials/learnjavaonline.org/en/Objects.md

class Point can't be public. This would be rejected

Fixed error in solution

---

tutorials/learncs.org/en/Lists.md

1 is not a Prime Number, so I removed it from the start of the list and added the next prime number (11) in order to retain the size of the list.

Fixed prime numbers

---

tutorials/learnjavaonline.org/en/Compiling and Running with Arguments.md

The Sphere Engine runs `Main.java`, which requires the `Main`
class to exist. Rename the tutorial code's class name
from `Arguments` to `Main`.

Refactor tutorial code's class to Main

---

tutorials/learnpython.org/en/Input and Output.md

The ide does not support Input operations but still taking input is necessary in any tutorial!

Create Input and Output.md

---

tutorials/learnpython.org/en/Basic String Operations.md

I have added some more information to basic string operations

Update Basic String Operations.md 

---

tutorials/learnpython.org/en/Closures.md

The tutorials are great, and I learn a lot from them. However, I encountered some issue on this page, hoping that my contribution can fix it. Open to comments!

Fixing some typos

---

tutorials/learn-php.org/en/Simple arrays.md

Corrected Misspelling

---

tutorials/learn-perl.org/Subroutines

This pull request contains a solution for the exercise in the Learn Perl Subroutines Chapter as well as some cleaning in the code examples before as:
* Consistent 4-space indent
* Warning free examples (Mainly adding my in variable declaration)
* No trailing whitespaces
If the latter is apprechiated, I can also have a look at the other chapters. Thanks for providing this tutorial!

Solution and Clean Code for Perl Subroutines Chapter

---

tutorials/learnpython.org/en/Basic String Operations.md

I believe these are preventing the solution from being identified as correct -- or at least making it a little more challenging ;)

Fix discrepencies in "Basic String Operations" Python tutorial

---

tutorials/learnpython.org/pl/Wyrazenia regularne.md

PL - Poprawienie literówek
EN - fix typos

Update Wyrazenia regularne.md

---

tutorials/learnpython.org/it/Ciao Mondo.md
tutorials/learnpython.org/it/Liste.md
tutorials/learnpython.org/it/Variabili e tipi.md
tutorials/learnpython.org/it/Welcome.md

The Italian tutorial is out of date, incomplete and in some parts the language is not great (I am a native speaker). I have started rewriting it and I'm basically just translating the english one. So far I have done 3 pages. Note that the page about lists ("Liste") was broken. I have fixed it and adjusted it a little. I have also started the flask application and tested the changes I made including the exercises.
If you like what I have done I will carry on when I have some time. 
Cheers

Started rewriting the python italian tutorial

---

tutorials/learnpython.org/pl/Moduly i pakiety.md

PL - Poprawienie literówek
EN - fix typos

Update Moduly i pakiety.md

---

tutorials/learn-c.org/en/Unions.md

Got rid of extra spaces in exercise expected output.

C union tutorial fix

---

tutorials/learn-js.org/en/Conditions.md

The Conditions tutorial comes before the Functions tutorial.  It might be difficult for beginning programmers to know that parameters passed to functions could be named.  I added a note to explain this.
An alternative would be to include this parameter in the provided code.
If it was meant to be challenging, there are no changes needed.

Added a hint about parameter naming

---

tutorials/learnpython.org/en/Loops.md

added space between arguments for better readability. 
21 line: xrange(3, 6) but 76 line: xrange(1,10)

readability, style consistency

---

tutorials/learn-perl.org/en/Conditional Decisions.md

Had issues pasting in solution code. See below:
@family = ('Homer', 'Moe', 'Maggie');
%shoe_color = ('Lisa' => 'red', 'Homer' => 'brown', 'Maggie' => 'pink', 'Marge' => 'blue', 'Bart' => 'yellow');
%shoe_size = ('Moe' => 9, 'Lisa' => 7, 'Homer' => 12, 'Bart' => 8, 'Maggie' => 4);
if (!exists($shoe_color{$family[0]}))
{
$shoe_color{$family[0]} = "black";
}
if (!exists($shoe_size{$family[0]}))
{
$shoe_size{$family[0]} = 99;
}
$size = $shoe_size{$family[0]};
if ($size >= 10)
{
print "$family[0] wears large $shoe_color{$family[0]} shoes size $size\n";
}
else
{
print "$family[0] wears $shoe_color{$family[0]} shoes size $size\n";
}
if (!exists($shoe_color{$family[1]}))
{
$shoe_color{$family[1]} = "black";
}
if (!exists($shoe_size{$family[1]}))
{
$shoe_size{$family[1]} = 99;
}
$size = …

Solution for conditional exercise

---

tutorials/learnpython.org/en/Closures.md
tutorials/learnpython.org/en/Code Introspection.md
tutorials/learnpython.org/en/List Comprehensions.md
tutorials/learnpython.org/en/Regular Expressions.md

The changes made are:
- Added the missing exercise for the Code Introspection tutorial.
- Fixed minor bugs both in the Regular Expressions and the List Comprehensions tutorials.
- Fixed typing and formatting errors in the Closures tutorial.

Minor fixes to English Python tutorial

---

tutorials/learn-c.org/en/Strings.md

Three quotation marks causes the program to break.

Broken Example Code

---

tutorials/learncs.org/en/Methods.md

Tripped up... Failed code due to unmatched capitalization.

Changed capitalization on "foo" in tutorial code.

---

tutorials/learn-c.org/en/Arrays and Pointers.md
tutorials/learn-c.org/en/Multidimensional Arrays.md
tutorials/learn-c.org/en/Welcome.md

Hi,
I have added two new tutorials on C: 1) Multidimensional arrays and 2) Arrays and pointers. Would be great if you take a look at them.
Thanks.

Two new tutorials on C

---

tutorials/learnpython.org/en/Sets.md

Adding some prints and removing useless code lines

Corrected tutorial for Sets

---

tutorials/learnpython.org/en/List Comprehensions.md

Updated ListComprehension tutorial

---

tutorials/learn-c.org/en/Arrays and Pointers.md

Fix mem overflow - 
allocating for 2 chars (let's assume 1 byte) and writing 2 pointers (e.g. 8 byte for 64 bit architectures) is gonna result in an overflow.

Update Arrays and Pointers.md

---

tutorials/learnrubyonline.org/en/Methods.md
tutorials/learnrubyonline.org/en/Welcome.md

I've added a basic introduction to methods tutorial for learnrubyonline.org. This tutorial doesn't cover parameters in methods as I am hoping to do a separate tutorial for that.

Adding Methods lesson to Ruby Tutorials

---

tutorials/learnrubyonline.org/en/Methods With Parameters.md
tutorials/learnrubyonline.org/en/Welcome.md

I've now created a Ruby tutorial for methods with parameters.

Adding Methods With Parameters Ruby tutorial

---

tutorials/learn-c.org/en/Pointers.md

Fix tutorials/learn-c.org/en/Pointers.md 

---

tutorials/learncs.org/en/Welcome.md

Simply adding a link to a tutorial that was missing in learncs.

Added a link to basic classes

---

tutorials/learncs.org/en/Strings.md

Added a ToString section to the string tutorial in learncs.

Added a ToString section to the string csharp tutorial

---

tutorials/learnpython.org/fr/Hello, World!
tutorials/learnpython.org/fr/Welcome.md

Began translating the Python tutos to french

---

tutorials/learnshell.org/en/File Testing.md

Please check if this is good enough. Thanks

Create File Testing.md

---

tutorials/learn-c.org/en/Binary trees.md

Hi,
here is a working example for the binary tree.
The original was missing the initialisation of the nodes.
I also cleaned up the messy formatting and added a task to accomplish.

Working example for binary tree with an assignment.

---

tutorials/learncs.org/en/Contributing Tutorials.md

Micro grammar fix

---

tutorials/learnjavaonline.org/en/Arrays.md
tutorials/learnjavaonline.org/en/Inheritance.md
tutorials/learnjavaonline.org/en/Interfaces.md

Have found some typos (Missing brackets and semicolons).
Sry for the second branch, I'am new to github/beginning to understand it.

Correcting Syntax typos

---

tutorials/learnjavaonline.org/en/Conditionals.md

There where some ';' missing in the Boolean example.

Correct Conditionals.md

---

tutorials/learnjavaonline.org/en/Inheritance.md
tutorials/learnjavaonline.org/en/Interfaces.md

I revised the wording and the examples for Inheritance. If you don't care for the revisions, don't use them.

Revised inheritance

---

tutorials/learncs.org/en/Class Properties.md

Create Class Properties.md

---

tutorials/learn-c.org/en/Pointer Arithmetics.md

Spellcheck on tutorial text

---

tutorials/learn-c.org/en/Static.md
tutorials/learn-c.org/en/Welcome.md

This tutorial covers a knowledge of static keyword and it's differences with global. 
Suggestions are welcome.

tutorial on static keyword

---

tutorials/learn-cpp.org/en/Variables and Types.md

The Variables and Types file had C (not C++) code for the last heading and the exercise. So I fixed it! You're welcome!! :smiley:

Fixed Accidental C Tutorial Copying

---

tutorials/learn-c.org/en/Multidimensional Arrays.md

This should fix the markup for the C tutorial "Multidimensional arrays" and allows the tutorial code to display properly. Previously every code line started with "c" and some of the markup made the code show as regular text (Image attached gives example of what it was like).
Also improves consistency with other tutorial markup.

Fixes issue where code doesn't display properly in Multidimensional Arrays (C)

---

tutorials/learnpython.org/en/Classes and Objects.md

Update Classes and Objects.md

---

README.md

Add details of prerequisites needed for development environment to function.

Add setup details

---

tutorials/learnshell.org/de/Variables.md
tutorials/learnshell.org/en/Variables.md

The Variables tutorial does not work because the expected output contains a comma in "Jan 1, 2000" but the rest of the tutorial does not mention inserting a comma.

Fix Variables tutorial for learnshell.org

---

tutorials/learn-c.org/en/Pointer Arithmetics.md

As there is no point in hardcoding addresses since they are different each time I changed the exercise slightly.
Closes #220

Fix C Pointers

---

tutorials/learnshell.org/en/Bash trap command.md

Fixing comment for bash trap command example.

Update Bash trap command.md

---

tutorials/learn-c.org/de/Unions.md

Translated unions into german because it wasn´t coverd in the german tutorial.

Translated unions into german

---

tutorials/learn-c.org/en/Multidimensional Arrays.md

Update MultiDimmensional Arrays tutorial. There was a missing comma in third eample

Missing comma

---

tutorials/learn-c.org/en/Arrays and Pointers.md
tutorials/learn-c.org/en/Arrays.md
tutorials/learn-c.org/en/Bitmasks.md
tutorials/learn-c.org/en/Dynamic allocation.md
tutorials/learn-c.org/en/Function Pointers.md
tutorials/learn-c.org/en/Hello, World!.md
tutorials/learn-c.org/en/Multidimensional Arrays.md
tutorials/learn-c.org/en/Pointers.md
tutorials/learn-c.org/en/Strings.md
tutorials/learn-c.org/en/Structures.md
tutorials/learn-c.org/en/Unions.md
tutorials/learn-c.org/en/Variables and Types.md
tutorials/learn-c.org/en/While loops.md

I've gone through the C tutorials and made some alterations for clarity and sense - fixing typos and rephrasing a couple of unclear sentences. 
It's all very minor fixes, just intending to improve readability.

Various small phrasing/grammar changes to the C tutorials

---

tutorials/learn-php.org/fr/Boucles for.md
tutorials/learn-php.org/fr/Boucles while.md
tutorials/learn-php.org/fr/Chaines.md
tutorials/learn-php.org/fr/Fonctions.md
tutorials/learn-php.org/fr/Objets.md
tutorials/learn-php.org/fr/Proposer des tutoriels.md
tutorials/learn-php.org/fr/Salut, tout le monde !.md
tutorials/learn-php.org/fr/Tableaux simples.md
tutorials/learn-php.org/fr/Tableaux à clés.md
tutorials/learn-php.org/fr/Variables et types.md
tutorials/learn-php.org/fr/Welcome.md

Here's a proposed translation of the PHP tutorial into French.

Proposed french translation of the PHP tutorial

---

tutorials/learnshell.org/en/Array-Comparison.md

Hi Ron,
I am impressed about your work.
Created an array comparison topic , kindly review

Array Comparison in Learning shell

---

tutorials/learnrubyonline.org/en/Conditional Statements.md
tutorials/learnrubyonline.org/en/Hello, World!.md

I fixed some spelling errors and things!

Fix some typos for Hello, World Ruby tutorial

---

tutorials/learn-c.org/en/Conditions.md
tutorials/learn-c.org/en/Welcome.md

This takes some ideas from the js conditionals.
I haven't included switch statements because they could probably be included in their own file later on.

Add a conditions tutorial to learn-c

---

tutorials/learn-c.org/en/Conditions.md

I had some accidentally added commas and bad indenting. I tested all of them this time.

Fix broken C code

---

tutorials/learn-c.org/en/Unions.md

The printf on line 15 was missing a ) after the args and the one on 16 was using %i instead of %c, which will print 33 instead of ! given the correct input

Fix broken testing code

---

tutorials/learncs.org/en/Conditionals.md
tutorials/learncs.org/en/Welcome.md

This was adapted from the conditionals tutorials for Java and C.

Add C# Conditionals tutorial

---

tutorials/learnjavaonline.org/en/Conditionals.md

Some of the English wording was strange and so I fixed it to make the instructions more clear. There were also minor typos that I fixed.

Correct typos and strange wording in English learnjavaonline.org Conditionals

---

tutorials/learn-golang.org/en/Loops.md
tutorials/learn-golang.org/en/Welcome.md

add Looping Tutorial in Golang

add: Golang - Loops Tutorial

---

tutorials/learn-cpp.org/en/Template Metaprogramming.md
tutorials/learn-cpp.org/en/Welcome.md

adds tutorial for Template Metaprogramming in C++

add: cpp - Template Metaprogramming

---

tutorials/learnshell.org/en/Array-Comparison.md

The bits of code in that tutorial were not correctly formatted as spans of code.

Fix formatting for code in Array-Comparison.md for learnshell.org

---

tutorials/learnpython.org/it/Formattazione delle stringhe.md

Completed the translation in italian.

Update Formattazione delle stringhe.md

---

tutorials/learn-js.org/en/Contributing Tutorials.md
tutorials/learn-perl.org/en/Contributing Tutorials.md
tutorials/learn-php.org/en/Contributing Tutorials.md
tutorials/learncs.org/en/For loops.md
tutorials/learncs.org/en/Methods.md
tutorials/learncs.org/en/While loops.md
tutorials/learnjavaonline.org/cn/代码格式.md
tutorials/learnjavaonline.org/en/Contributing Tutorials.md
tutorials/learnjavaonline.org/en/Conventions.md
tutorials/learnpython.org/en/Contributing Tutorials.md
tutorials/learnpython.org/en/Input and Output.md
tutorials/learnpython.org/es/Input and Output.md
tutorials/learnrubyonline.org/en/Contributing Tutorials.md
tutorials/learnshell.org/en/Contributing Tutorials.md

Noticed a few typos and did some bulk replaces.

Fixed typos

---

tutorials/learn-js.org/en/Manipulating Arrays.md

in "Splicing", the splice was created as (3,5) and then the console.log listed the numbers 3-7 rather than 3-5, so I suggest changing the second integer in the splice method to 7.

Update Manipulating Arrays.md

---

tutorials/learnrubyonline.org/en/Check If A String Exists in The Certain String.md

Here I create a tutorial on how to check if a given string exists in a certain string. Please have a look :)

Tutorials on checking if a string exist in a certain string

---

tutorials/learnshell.org/en/Pipelines.md
tutorials/learnshell.org/en/Welcome.md

This pull request add a tutorial about shell pipes. I intend to complete the process substitution tutorial and thought it would be interesting to provide a pipes tutorial first.

add pipelines tutorial

---

tutorials/learn-html.org/en/Basic Elements.md

Thought this section of the tutorial could use an exercise. Test understanding of header tags in html.

added hmtl basic elements exercise

---

tutorials/learn-php.org/en/Exceptions.md

Learn how to cope with exceptions in PHP using try, catch and finally.

Exceptions.md

---

tutorials/learn-perl.org/en/Loops.md

Fixed code that wouldn't even compile previously nor do the intended action

Fixed incorrect code in Loops.md

---

tutorials/learnpython.org/en/Map, Filter, Reduce.md
tutorials/learnpython.org/en/Welcome.md

A detailed tutorial on Python's Map, Filter, and Reduce

Added Map, Filter and Reduce

---

tutorials/learn-c.org/en/Arrays.md

It wasn't clear to me whether to remove the TODO comments.
If you approve this, I'll add the solution to the other languages.
FYI, the checker is too liberal for this problem. It passes even if I declare int grades[1];

Added solution to en/Arrays.md

---

tutorials/learn-perl.org/en/Conditional Decisions.md
tutorials/learn-perl.org/en/Regular Expressions.md

Also removed trailing whitespace.
Loved the tutorials! This was seriously cool.

Fixed tiny typos

---

tutorials/learnpython.org/en/Exception Handling.md

Added Function and call so the parser creates a code window that shows the whole block of code

Fix for short code window

---

tutorials/learnpython.org/es/Basic Operators.md

adding solution for operators exercise

Update Basic Operators.md

---

tutorials/learn-cpp.org/en/Functions.md

Added function.md tutorial to learn-cpp.org! Hope to contribute much more

Added function.md tutorial to learn-cpp.org

---

tutorials/learnpython.org/en/Conditions.md

Updated Conditions.md

---

tutorials/learn-c.org/de/Variables and Types.md
tutorials/learn-c.org/en/Variables and Types.md
tutorials/learn-c.org/nl/Variables and Types.md
tutorials/learn-cpp.org/de/Variables and Types.md
tutorials/learn-cpp.org/en/Variables and Types.md

Fix https://github.com/ronreiter/interactive-tutorials/issues/408

[C] Fix format

---

tutorials/learnsqlonline.org/es/Aggregate functions.md
tutorials/learnsqlonline.org/es/Creating tables.md
tutorials/learnsqlonline.org/es/Deleting rows.md
tutorials/learnsqlonline.org/es/Distinct queries.md
tutorials/learnsqlonline.org/es/Group by.md
tutorials/learnsqlonline.org/es/Hello, World!.md
tutorials/learnsqlonline.org/es/Inserting rows.md
tutorials/learnsqlonline.org/es/Joining tables.md
tutorials/learnsqlonline.org/es/Order by.md
tutorials/learnsqlonline.org/es/Selecting data.md
tutorials/learnsqlonline.org/es/The HAVING statement.md
tutorials/learnsqlonline.org/es/Updating rows.md
tutorials/learnsqlonline.org/es/Welcome.md

Added spanish language in sql tutorials

Added ES language in SQL

---

tutorials/learnjavaonline.org/en/Compiling and Running.md
tutorials/learnjavaonline.org/en/Variables and Types.md

Added information in boolean and string 

---

tutorials/learnjavaonline.org/en/Conditionals.md

The Problem:
The previous conditionals tutorial required explicitly creating a nonfunctional `.equals` method, such that `b.equals(b + "!")` would return true. This was not explicitly testing the concepts covered in the tutorial above.
The Solution:
Fixed one variable reference in the problem such that the solution is now more similar to the starter code, involving String variable assignment. Also updated the solution code to match.

update Java conditionals tutorial

---

tutorials/learn-js.org/en/Function Context.md
tutorials/learnjavaonline.org/en/Using Generics.md

JS:
Function Context:
Clarified difference between call/apply and bind
Java:
Generics:
Added generics for class, constructor, method, and property declaration and usage, updated exercise to match

JS call/apply/bind and Java generics

---

tutorials/learn-c.org/en/Linked lists.md

Same as #428, but for the linked lists tutorial step. Although I wonder if this isn't unnecessarily adding complexity as it is not required for C, but I'm guessing you have your reasons for using a C++ compiler instead.
Thanks for the great work and timely responses, by the way!

cast malloc return value in linked lists tutorial too

---

tutorials/learn-c.org/en/Binary trees.md

- Cast `malloc` return value to type (same as #428 and #429)
- Fix typo `ov` to `of`
- Some CS fixes

fix binary trees C tutorial

---

constants.py
tutorials/learnpython.org/pl/Zmienne i typy.md

Print is a function in Python 3.

Fix Hello World example for Python

---

tutorials/learncs.org/en/Arrays.md
tutorials/learncs.org/en/Basic Classes.md

In new C# version, there is another type of Arrays called Jagged Array So arrays must contain these types to keep the readers updated with the newest version of C#.

Adding Jagged Array

---

tutorials/learncs.org/en/Arrays.md
tutorials/learncs.org/en/Basic Classes.md

I have Added Partial Classes in the Class tutorial.

Added partial Classes

---

tutorials/learnpython.org/es/Basic String Operations.md

Translation [EN>SP] - some paragraphs
Fixed typos
Corrected indexes mistakes caused by having used for the examples "Hello World!" instead of "Hola Mundo!"

Update Basic String Operations.md

---

main.py

I have written Turkish pages for learnshell but It didn't show up in the site. So I changed the code in main.py to recorganize tr directory.

Added Turkish lang option

---

tutorials/learn-js.org/pl

Welcome.pl

---

tutorials/learnpython.org/pl/Welcome.md

Welcome.md

---

tutorials/learnpython.org/es/List Comprehensions.md

Translate example from English to Spanish and delete a repeated paragraph

Traslate List Comprehensions.md

---

tutorials/learnpython.org/es/Basic Operators.md

I 've edited the example code, because it was in English. Also I made some redaction improves to make it  more clear.

Translate for improving spanish version

---

tutorials/learnpython.org/es/Generators.md

Translate Generators explanation

Traslate Generators.md

---

tutorials/learnpython.org/es/Regular Expressions.md

I've noticed that this ".md" isn't in spanish so I've made some changes on it. Hope it worth!

Python Improving Spanish Version Regex

---

tutorials/learnpython.org/en/Basic String Operations.md
tutorials/learnpython.org/en/Functions.md

Add missing space after period.

---

tutorials/learn-php.org/en/Multidimensional arrays.md
tutorials/learn-php.org/en/Welcome.md

Hello,
Please add this tutorial about Multidimensional arrays.

➕ Add tutorial about Multidimensional arrays.

---

tutorials/learnpython.org/es/Functions.md

Add Spanish solution to learnpython - Functions
Add spanish translation learnpython - ExpectedOutput

Spanish improvements in learnpython

---

tutorials/learnpython.org/es/Welcome.md

Fixed orthographic and grammatical errors in Spanish translation. Change in wording to increase fidelity with the English version. **-** **Welcome (es)**

Fixed errors in Spanish translation.

---

tutorials/learnpython.org/en/Map, Filter, Reduce.md

There was a spelling mistake, so edited it from "retuns" to "returns"

Update Map, Filter, Reduce.md

---

tutorials/learnjavaonline.org/en/Generic Types.md

I have created a tutorial for generic types

Generic Types

---

tutorials/learn-c.org/en/Conditions.md

This warning exists in the Functions tutorial, but the tutorial for conditions also expects newline characters.

add newline char warning - conditions (c tutorial)

---

tutorials/learn-cpp.org/en/Linked lists.md

It was driving me crazy, so I fixed it. I tried to match the style of the other classes defined in the tutorial.

fix formatting in Linked lists.md

---

tutorials/learn-html.org/en/Drag and Drop.md

I developed this exercise. Please review it and add to the repo.

Update Drag and Drop.md

---

tutorials/learn-html.org/en/Styles.md

Change the href to match the file name

Fixed typo in Styles.md

---

tutorials/learnpython.org/en/Dictionaries.md

Fix exercise section

---

tutorials/learnpython.org/es/String Formatting.md

Update String Formatting.md

---

tutorials/learncs.org/en/Basic Classes.md
tutorials/learncs.org/en/Class Properties.md
tutorials/learncs.org/en/Class Variables.md
tutorials/learncs.org/en/Welcome.md

Re-submitting pull request after merging in latest changes from master.

Rickhaws add properties

---

tutorials/learnpython.org/es/Loops.md

Hi again!  I 've edited the example code, because it was in English. Also I made some redaction improves to make it more clear.

Python Translate for improving spanish version

---

tutorials/learnjavaonline.org/en/Objects.md
tutorials/learnjavaonline.org/en/Try and Catch.md

"we **wan't** get an accurate value" -> "we **won't** get an accurate value"
"..., **than** make it print" -> "..., **then** make it print"

tutorial-java-objects: fix typo

---

tutorials/learnsqlonline.org/en/Creating tables.md

Organized the sections of the code.

Update Creating tables.md

---

tutorials/learn-js.org/en/Conditions.md

Fix typo from `an` to `and` and add oxford comma

---

tutorials/learn-c.org/en/Hello, World!.md

* Replaced "line" with "statement"

Update Hello, World!.md

---

tutorials/learn-cpp.org/en/Function arguments by reference.md

Fixed typo in "Function arguments by reference"

---

tutorials/learn-cpp.org/en/Strings.md

fix typo in Strings.md

---

tutorials/learnshell.org/en/Passing Arguments to the Script.md

Added content to Exercise, tutorial code ,solution and expected output

Update Passing Arguments to the Script.md

---

tutorials/learn-perl.org/en/Loops.md

Signed-off-by: bsantanad <0211518@up.edu.mx>

small typo in perl Loops.md

---

main.py
templates/sitemap.xml
templates/sitemap_index.xml

Added sitemap.xml

---

tutorials/learnpython.org/en/CsvPython.md

CSV module in python

---

tutorials/learn-cpp.org/de/For loops.md
tutorials/learn-cpp.org/de/Welcome.md
tutorials/learn-cpp.org/de/if-else.md

I added the German turorial and exercise for c++ for-loops and also for if-else statements.

Adding German md-page for c++ for-loops and if-else

---

tutorials/learn-js.org/en/Loops.md

As the Array index starts with 0 there is no use for "=" operator while dealing with Array.length. Typing a "=" operator along with less than operator will not give the Expected Output and shows a "Undefined Value" in Output. Thanks learn-js.org!

Removed "=" in Loop Condition on Loops.md

---

tutorials/learn-c.org/en/Function arguments by reference.md

The error can be found on https://www.learn-c.org/en/Function_arguments_by_reference
> Assumingly _you're already know_ pointers and functions, so you are _aware of that_ function arguments are passed by value...
> Assumingly, you already know pointers and functions, so you are aware that function arguments are passed by value...

Fix grammatical error

---

tutorials/learn-c.org/en/Dynamic allocation.md
tutorials/learn-c.org/en/Function arguments by reference.md

The dynamic allocation page used the malloc() function, but never explicitly explained it's purpose.

Added an explanation of the memory allocation function

---

README.md

Fixed some ambibuity in README.md

---

tutorials/learnRust.org/Hello World!.md

Added solution for challenge in hello world exercise.

Added Solution

---

tutorials/learn-c.org/en/Dynamic allocation.md

Changed a repeated have to sound a bit more expressive.

Changed repeated have to need

---

tutorials/learnshell.org/en/Decision Making.md

$case is now called $mycase and does not need more explanation

Remove obsolete explanation

---

tutorials/learn-html.org/en/JavaScript.md

I added content to this tutorial. The page was blank.
I did this because JavaScript was really important for web developers.

JavaScript.md

---

tutorials/learnpython.org/en/Classes and Objects.md

Added __init__()

---

tutorials/learncs.org/en/Foreach loops.md

Added `foreach` loop tutorial.

Foreach loops.md

---

tutorials/learn-html.org/en/Hello, World!.md

Added definition of `<!DOCTYPE html>`.

Hello, World!.md

---

tutorials/learn-html.org/en/JavaScript.md

I fixed some spelling errors and some Markdown formatting errors.

JavaScript.md Update

---

tutorials/learn-html.org/en/JavaScript.md

Fixed one formatting error and a small bug.

Fix JavaScript.md

---

tutorials/learncs.org/en/Foreach loops.md

Fix Foreach loops.md

---

tutorials/learnpython.org/pl/Podstawowe operatory.md

Added solution to python tutorial in Polish "Podstawowe operatory.md"

Dodane rozwiązanie

---

tutorials/learnpython.org/pl/Tablice.md

Added solution to python lists tutorial in Polish "Tablice.md"

Added solution to Tablice.md

---

tutorials/learn-js.org/en/Conditions.md

Adding to for grammatical reasons

Grammar fix

---

tutorials/learnshell.org/en/Passing Arguments to the Script.md

I am beginner to shell and here I try to make easily understandable to other user like me. Before writing this as beginner I learn shell by moving forward tutorial. I just tries to improve the example if any changes need I would like to know.

Changes according to the Exercise and improve example

---

tutorials/learn-js.org/en/Destructuring.md
tutorials/learn-js.org/en/Function Context.md

🎯Fixed and changed some of the text in the reading part of the documentation for better and easy understanding.
_🤝Preview the changes through the screenshots provided-_
-----------------------------------------------------------------------------------------------------------------------------------------

Fixed grammatical issues in the Documentation.

---

tutorials/learn-cpp.org/en/Inheritance.md

Fix imaginary part of the `c1` in the expected output. 
Add detail to the solution.

Fix some errors in Inheritance.md

---

tutorials/learn-cpp.org/en/if-else.md

the comments (lines 84-85) were hashtags instead of double forward slashes so the compiler (or whatever checks the program) would throw an error when the user has done nothing wrong

fixed tutorial bug that would throw error

---

tutorials/learnpython.org/en/Modules and Packages.md

I found some sections of the Python tutorial I thought I could improve. It's been a really helpful refresher on Python though. Let me know if you have any questions.

Python tutorial revisions

---

tutorials/learn-js.org/en/Variables and Types.md

Change all var to const (I will continue adding more commits when I can)

Change var to const

---

tutorials/learn-php.org/fr/Exceptions.md
tutorials/learn-php.org/fr/Tableaux multidimensionnels.md
tutorials/learn-php.org/fr/Welcome.md

Adding the 2 new pages translated to french.
Not yet adding the math operators page, as it is not linked from the welcome page in English

Add translations for new pages

---

tutorials/learn-php.org/fr/Objets.md
tutorials/learn-php.org/fr/Salut, tout le monde !.md

Fix a few tiny typos in french translations

---

tutorials/learn-c.org/es/Arrays.md
tutorials/learn-c.org/es/Binary trees.md
tutorials/learn-c.org/es/Conditions.md
tutorials/learn-c.org/es/For loops.md
tutorials/learn-c.org/es/Functions.md
tutorials/learn-c.org/es/Hello, World!.md
tutorials/learn-c.org/es/Multidimensional Arrays.md
tutorials/learn-c.org/es/Recursion.md
tutorials/learn-c.org/es/Static.md
tutorials/learn-c.org/es/Strings.md
tutorials/learn-c.org/es/Variables and Types.md
tutorials/learn-c.org/es/Welcome.md
tutorials/learn-c.org/es/While loops.md

There are some missing but I'm sending these so far. I will be completing the rest once these are accepted :)

Add Spanish translations for learn-c.org

---

main.py

Fixes #635 
> Detect file system change and auto reload the server

Added functionality - Detect file system change and auto reload the server

---

tutorials/learn-js.org/en/Promises.md

I know this is kinda minor but I was confused for a bit because of this

Add missed parenthesis and semicolon

---

tutorials/learn-c.org/en/Multidimensional Arrays.md

Changed from "you could say, but, you need need NEED a [ y ] value!!" TO "you could say, but, you NEED a [ y ] value!!".

Removed unnecessarily repeating of the word need.

---

tutorials/learnpython.org/en/Modules and Packages.md

closes security issues in the dockerfile
[Dockerfile fix](https://github.com/ronreiter/interactive-tutorials/commit/872d27481d963bbba8c0da793d6ab91f014378b5)

upgrade python

---

tutorials/learn-c.org/es/Arrays.md
tutorials/learn-c.org/es/Hello, World!.md
tutorials/learn-c.org/es/Multidimensional Arrays.md
tutorials/learn-c.org/es/Strings.md
tutorials/learn-c.org/es/Variables and Types.md

Correction of grammatical errors and correction of a misdirected link.

Correction of grammatical errors in Spanish files

---

tutorials/learn-js.org/en/Function Context.md

changed 'variable' to  'keyword'

js-this-keyword

---

tutorials/learn-golang.org/en/If-Else.md

Hi, I was using this tutorial just now to learn Go and ran into errors using the code examples. Just want to fix 2 variables not declared with the right syntax.

Fixing variable declarations

---

tutorials/learn-html.org/en/Box Model.md

What I Did:
•	Added a new Markdown tutorial file css-box-model.md under the tutorials directory.
•	Explained the CSS Box Model in detail, covering content, padding, border, and margin.
•	Included a diagram to help visualize the box model.
•	Provided an exercise where users modify a div element using CSS properties.
•	Added expected output and a solution for verification.

Added CSS Box Model tutorial

---

tutorials/learn-c.org/en/Dynamic allocation.md

I may be wrong but I feel like there is a small error, see the changes i suggest. If I'm wrong, please tell me why

Learn C - Update Dynamic allocation.md

---

tutorials/learnpython.org/en/Input and Output.md

Fixed Print in Output Formatting
