tutorials/learn-perl.org/Regular Expressions

BACKTRACKING example displayed errors as follows:
Scalar found where operator expected at prog.pl line 3, near ""The telephone number extracted is "$1"
(Missing operator before $1?)
String found where operator expected at prog.pl line 3, near "$1"\n""
(Missing operator before "\n"?)
syntax error at prog.pl line 3, near ""The telephone number extracted is "$1"
Execution of prog.pl aborted due to compilation errors.
Minor modification and code is now fixed!

Update Regular Expressions.md

---

tutorials/learn-perl.org/en/Conditional Decisions.md

syntax errors from 'if statements' now fixed as follows 
$x = 5;
$y = 10;
if ($x == 5)  {
print "x is indeed 5\n"; 
} 
if ($y == 5) { 
print "y is indeed 5\n"
}
else {
print "y is not 5\n";
} 
$my_result = ($y == 5) ? "y is indeed 5" : "y is not 5";  {
print "My result is: $my_result\n";
}
if ($x > $y)  {
print "Result is:\n";
print "x ($x) is greater than y ($y)\n";
} 
elsif ($my_result eq "y is not 5")  {
print "Result is:\n";
print "I know that $my_result\n";
} 
else {
print "Result is:\n";
print "x ($x) is not greater than y ($y)\n";
}

Update Conditional Decisions.md

---

tutorials/learnpython.org/en/Closures.md

The link fro the main page states "Closures", the title in the page generically says "Tutorial", made me wonder if I actually followed the right link :-)

Fixing title, from generic "Tutorial" to "Closures"

---

tutorials/learnshell.org/en/Special Variables.md

Exact command name for "The number of argument passed to script or function." is $#, not $.

Fix a command name for "The number of argument"

---

tutorials/learnrubyonline.org/en/Methods With Parameters.md
tutorials/learnrubyonline.org/en/Methods.md

Fixing some typos in both Ruby methods tutorials. It wasn't formatted properly in the Markdown files.

Fixing typos in Markdowns

---

tutorials/learncs.org/en/Basic Classes.md

The example in the C# Basic Classes tutorial previously gave an error because the Main class and Main function had the same name. Additionally, the expected output should be "True", not "true".

Changed example for C# Basic Classes

---

tutorials/learnjavaonline.org/en/Objects.md

In the exercise of Java's Chapter Object, the public class were defined
twice, which caused a compilation error.

Bug fix: resolve the compilation error in Java's Chapter Object.

---

tutorials/learn-c.org/en/Static.md

This cleans up grammatical and spelling mistakes in the C tutorial on the `static` keyword, introduced by pull request #264.  In doing so, I tried to stick to the original pedagogy as closely as possible.

cleanup spelling/grammar for C static tutorial

---

tutorials/learn-golang.org/en/Variables.md

The suggested solution did not pass the expected output verification
due to a typo.

golang variables: fix typo in solution output

---

tutorials/learn-php.org/en/Welcome.md

Long time ago I've created Exceptions tutorial, but it looks like its unaccessible from main page and doesn't appears at the Main page.

Added link to Exceptions

---

tutorials/learn-php.org/en/Exceptions.md

Previously the format was geared towards markdown which did not transfer properly over to the site.
These changes fix the the format as well as improve the tutorial code.
The old tutorial code used an example of division by a zero, however the online php compiler does not throw a catchable exception for division by zero, it throws a warning.

Reformat and Improve PHP Exceptions tutorial

---

tutorials/learn-c.org/de/Dynamic allocation.md
tutorials/learn-c.org/en/Dynamic allocation.md
tutorials/learn-c.org/nl/Dynamic allocation.md

Currently the Dynamic allocation tutorial requires no changes to pass. It will include warnings:
```
malloc: *** error for object 0x7ffee039e910: pointer being freed was not allocated
malloc: *** set a breakpoint in malloc_error_break to debug
```
But still pass.
Setting the pointer specifically to `NULL` requires code changes to make the exercise pass, as it prints nothing by default now.

C - Require code changes to pass Dynamic Allocation Tutorial

---

tutorials/learn-c.org/en/Dynamic allocation.md

To match solution after 3b26a7564051bc0c196327cd2f15a897b062e8c5, should the tutorial itself also cast the `malloc` return value?
I was confused by the error returned when not casting `malloc`'s return value, despite using the exact same code as in the accompanying text.
```c
prog.cpp: In function ‘int main()’:
prog.cpp:12:27: error: invalid conversion from ‘void*’ to ‘point*’ [-fpermissive]
point * mypoint = malloc(sizeof(point));
~~~~~~^~~~~~~~~~~~~~~
```

cast malloc return

---

tutorials/learnpython.org/fr/Variables and Types.md

Restored English section titles to achieve correct parsing, esp. in sect. "Tutorial Code" and following. Some other minor improvements in the contents of the lecture. (How to include both ' and " and newline character in strings; result of `str * int` which is allowed.)

Bug fix in "Variables & Types" [fr]

---

tutorials/learn-js.org/en/Manipulating Arrays.md

So while learning JS I found this mistake.
`shift` removes element, so is similar to `pop`.
`unshift` adds element, so is similar to `push`.
Hence the proper wordings should be : *The `unshift` and `shift` methods are similar to `push` and `pop`* instead of *The `shift` and `unshift` methods are similar to `push` and `pop`*.

Update Manupulating Arrays.md; fixed a mismatch

---

tutorials/learn-html.org/en/Basic Elements.md

In the *horizontal ruler* section, the demo code snippet uses `<hr/>` instead of `<hr>`. Though it doesn't affect the output, it confuses newbies, like *why a `/`? Is it part of syntax?*

Update Basic Elements.md, removed ambiguity of hr tags.

---

tutorials/learn-c.org/en/Functions.md

Tweaked exercise instructions to clarify not to literally print "x is big" but rather clarify x is the function argument

addtl clarity in exercise Functions (c tutorial)

---

tutorials/learn-c.org/en/Arrays and Pointers.md

Maybe I'm the only one who got this, but I was getting char * is incompatible pointer type warning when using the old example. I modified the code and changed the unsigned integer to the pointer address in memory. Seems a bit easier to read?
If I'm still doing something wrong here, maybe there is a way to avoid the incompatible pointer type error and still use your example.

Update Arrays and Pointers with memory addresses

---

tutorials/learn-html.org/en/Images.md

was using "class" in the second paragraph in the Using the CSS float attribute with images section. I fixed it to style instead.

Fixed a typo in Images.md

---

tutorials/learnpython.org/en/Map, Filter, Reduce.md

As per the given solution, the results are rounded to **3 decimal places** and **not 2 decimal places**, now the comments in the question have been **corrected to reflect this**.

Added fix for issue: #499

---

tutorials/learncs.org/en/Methods.md

Changed typo in method name in the exercise. It was typed as "foo" but should be "Foo" since method names in C# should start with capital letters. The solution code already had the right capitalization

Fix typo in Methods.md

---

tutorials/learn-cpp.org/en/Variables and Types.md

Expected solution defines there should be a space between the "is" and the sum value.
Fixes the tutorial starting code to add in this space

CPP: Fix Variables & Types Tutorial Bug

---

tutorials/learn-cpp.org/en/Variables and Types.md

Highlight in current example is broken due to invalid var names.

Imrpove example readability in Variables and Types.md

---

tutorials/learn-c.org/en/Dynamic allocation.md

Introducing typecasting without an explanation may confuse learners and make it hard to understand what the different statements in the dynamic allocation syntax exactly do.

C: Explain typecasting in Dynamic Allocation tutorial

---

tutorials/learnshell.org/de/Decision Making.md
tutorials/learnshell.org/en/Decision Making.md
tutorials/learnshell.org/tr/Koşullu Durumlar.md

There is a tiny bug on https://www.learnshell.org/en/Decision_Making Logical Combinations chapter. Spotted by @MaatheN
This => `if [[ $VAR_A[0] -eq 1 && ($VAR_B = "bee" || $VAR_T = "tee") ]] ; then` is displayed like this => `if <a href='/en/_%24VAR_A_-eq_1_%26%26_%28%24VAR_B_%3D_%22bee%22_'>| $VAR_T = "tee") </a> ; then`
This is due to wikify function which use double brackets to detect wiki links. To solve the underlying issue, it would be necessary to change the way wiki links are detected but this tiny fix just avoid the issue by modifying the code example. This code example  is still relevant to the rest of the tutorial.

fix display bug related to usage of double bracket [[

---

tutorials/learn-c.org/en/Linked lists.md

Assigning previous and current to (*head)->next before the while loop will cause and error if the value being searched for is after the head of the list.  In this case 2. Since previous and current point the to same location before the while loop. It will hit the if statement before reassigning previous.  So previous->next already equals current->next.  This causes an error since freeing current would be freeing where previous is pointing.
Fixed this by assigning previous to current on line 353 and moving the current assignment of (*head)->next down to line 354.

Error in Learn-C Linked List Solution

---

tutorials/learn-c.org/de/Linked lists.md
tutorials/learn-c.org/en/Linked lists.md
tutorials/learn-c.org/nl/Linked lists.md

Account for edge case in `remove_by_index` when index = size of the array.
Error example:
```c
int main() {
node_t * head = malloc(sizeof(node_t));
if (head == NULL)
return 1;
head->next = NULL;
head->val = 5;
int ret = remove_by_index(&head, 1);
printf("Returned: %d\n", ret);
printf("Head pointer: %p\n", head);
}
```

Fix segfault in learn-c.org/xx/Linked lists.md

---

tutorials/learn-perl.org/en/Loops.md

Fixed a typo and updated 'until' loop description to have correct information

Perl Loops.md: Correct Typo and Information

---

tutorials/learn-js.org/en/Function Context.md

✌️There was a repetition of a certain phrase in the documentation of Function Context - call/apply vs bind. The phrase - 
"return a" was repeated twice. Fixed the typo.
🌱You can find the fixation in the screenshot provided-
.

🎯Updated the documentation of Function Context.

---

tutorials/learnpython.org/en/Functions.md
tutorials/learnpython.org/en/Loops.md
tutorials/learnpython.org/en/Modules and Packages.md

These three commits remove ambiguity for students due to the fact that the pass/fail requirement of the last exercise needs a specific variable name that is not shown to the student until they attempt to run their code. Adding these variable names directly into the exercises lessens the chances of a false negative.
Also removing the pass keyword as it was never explained.

Removing ambiguity in final exercises

---

tutorials/learnpython.org/it/Variabili e tipi.md

Traceback (most recent call last):
File "/usr/lib/python3.5/py_compile.py", line 125, in compile
_optimize=optimize)
File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
File "./prog.py", line 8
print "Stringa: %s" % mystring
^
SyntaxError: Missing parentheses in call to 'print'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/lib/python3.5/py_compile.py", line 129, in compile
raise py_exc
py_compile.PyCompileError:   File "./prog.py", line 8
print "Stringa: %s" % mystring
^
SyntaxError: Missing parentheses in call to 'print'

Missing parentheses in call to 'print'

---

tutorials/learn-cpp.org/en/Pointers.md

I noticed that the part within the exercise where it says "p2 must be assigned to p1" was wrong, contrary to the solution provided and also to the assignment in question, so I changed that part to "p1 must be assigned to p2".
I also noticed that there could have been a problem with formatting the exercise so I made an attempt at fixing the formatting, hopefully.

Fixed C++ pointers exercise assignment and reformatted for readability 
